### ISSUE TITLE
docker-ce阿里镜像源url失效

### ISSUE THREAD

**Issue by jdmw** [dotbalo/kubernetes-guide#1]
你好！
本书第一章第3页，添加docker-ce源
原文命令： yum-config-manager --add-repo http://mirrors.aliyun.com/docker-lce/linux/centos/docker-ce.repo
中间这个1和l太像，于是docker-lce和docker-1ce我两个都试了，链接都不存在
目前可用的链接是：http://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo ，请问效果是不是相同的？

**Comment by dotbalo** [comment]
可能是排版或印刷导致的问题，正确应该是docker-ce，并不是docker-lce
