### ISSUE TITLE
Unable to update cni config: no networks found in /etc/cni/net.d

### ISSUE THREAD

**Issue by cnq50** [dotbalo/kubernetes-guide#2]
我再添加node节点时报这个错，请问一下是什么原因，我是完全按照书上的步骤去安装的

**Comment by dotbalo** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        您好，
            不好意思，这个报错像是没有cni插件引起的。    以后有什么问题可以加群：780043119
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                dukuan.china
                            
                    
                        
                            
                                    dukuan.china@gmail.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 5/3/2020 02:00，cnq<notifications@github.com> wrote： 




我再添加node节点时报这个错，请问一下是什么原因，我是完全按照书上的步骤去安装的



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
