### ISSUE TITLE
unknow tooken

### ISSUE THREAD

**Issue by rushoo** [dotbalo/kubernetes-guide#4]
《云原生kubernetes全栈架构师实战》page42
`kubectl config set-credentials tls-bootstrap-token-user --token=c8ad9c.2e4d610cf3e7426e --kubeconfig=/etc/kubernetes/bootstrap-kubelet.kubeconfig`
不知道这里的token应该从哪里获取的

**Comment by dotbalo** [comment]
您好，这里的token字符可以随便写的。
